#################################
#####          标题         #####
#################################
time: 4                      #单位tick,默认显示时间=信息总长度*time,>=0
interval: 15                #单位tick,>=0,连接显示的间隔(一条显示结束后,下一条显示开始前等待的时间)
fadeIn: 15                  #单位tick,>=0
fadeOut: 15                 #单位tick,>=0